
server:
  domain: "1omztyeuf8ch.xiaomiqiu.com"
  host: "0.0.0.0"
  port: 8080
  certPath: "./cert.pem"
  keyPath: "./key.pem"

copilot:
  github_api_url: https://api.github.com/copilot_internal/v2/token
  tokens:
    - "ghu_HvsEzGqmlyJOyBc7sSJGYT3CW1oTsk4Y73cJ"
    - "ghu_uvuazpzcbZK0fghOA4fdo1BsLYNwtZ2fhzaV"

secret: